config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :users
  #resources :login_cuidadores_pgs
  #get 'sign_in' =>  'login_cuidadores_pgs#new'
  #post 'sign_in' => 'login_cuidadores_pgs#create'
  #delete 'sign_out' => 'login_cuidadores_pgs#destroy'
  #resources :login_clientes_pgs
  #get 'entrar' =>  'login_clientes_pgs#new'
  #post 'entrar' => 'login_clientes_pgs#create'
  #delete 'sair' => 'login_clientes_pgs#destroy'
  resources :lista_cuidadores
  resources :pag_cuidadores
  #resources :instrucoes
  #resources :home
  resources :pag_clientes
  #resources :sobre
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :usuarios
  root :to => "home#home"
  get 'ajuda' => 'instrucoes#index'
  get 'sobre'  => 'sobre#sobre'

  get    'login',   to: 'sessions#new'
  post   'login',   to: 'sessions#create'
  delete 'logout',  to: 'sessions#destroy'


=begin
  match 'show_usuario' => 'usuarios#show', via: 'get'
  match 'edit_usuario' => 'usuarios#edit', via: 'get'
  match 'new_usuario' => 'usuarios#new', via: 'get'
  match '' => 'usuarios#create', via: 'post'
  match '' => 'usuarios#update', via: 'patch'
  match '' => 'usuarios#update', via: 'put'
  match '' => 'usuarios#destroy', via: 'delete'
=end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/instrucoes.rb
class Instrucoes < ApplicationRecord
end

app/models/lista_cuidadore.rb
class ListaCuidadore < ApplicationRecord
end

app/models/login_clientes_pg.rb
class LoginClientesPg < Usuario
end

app/models/login_cuidadores_pg.rb
class LoginCuidadoresPg < Usuario
end

app/models/pag_clientes.rb
class PagCuidadore < ApplicationRecord
end

app/models/pag_cuidadores.rb
class PagCliente < ApplicationRecord
end

app/models/pag_login_clientes.rb
class PagLoginCliente < ApplicationRecord
end

app/models/pag_login_cuidadores.rb
class PagLoginCuidadore < ApplicationRecord
end

app/models/sobre.rb
class Sobre < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
   before_save {self.email = email.downcase! }
   attr_accessor :nome, :idade, :email, :cidade, :estado, :ser #:password, :password_confirmation
   validates_presence_of :ser, :idade,:cidade, :estado #:password ,:password_confirmation
   #Confirmação de senha
   #validates_confirmation_of :password
   #Validação do formato de email
   validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
   #Verifica se não existe outro registro de e-mail no banco de dados que tenha a mesma informação;
   validates :email, presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: false }
   validates :nome, presence: true, length: { maximum: 50 }
   has_secure_password
   #Tamanho mínimo da senha
   validates :password, presence: true, length: { minimum: 6}
   # Returns the hash digest of the given string.


end

app/models/usuario.rb
class Usuario < ApplicationRecord
  attr_accessor :nome, :idade, :email, :cidade, :estado, :password, :password_digest
  #valida se o usuarios tiver todos os dados presentes.
  validates_presence_of :nome, :idade, :email, :cidade, :estado, :password
  #verifica se o preenchimento do campo é numérico;
  validates_numericality_of :idade;
  #Confirmação de senha
  validates_confirmation_of :password
  #Validação do formato de email
  validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
  #Verifica se não existe outro registro de e-mail no banco de dados que tenha a mesma informação;
  validates_uniqueness_of :email

  #Tamanho mínimo da senha
  validates :password, length: { minimum: 6}
  has_secure_password



end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/lista_cuidadores_controller.rb
class ListaCuidadoresController < ApplicationController
  before_action :set_lista_cuidadore, only: [:show, :edit, :update, :destroy]

  # GET /lista_cuidadores
  # GET /lista_cuidadores.json
  def index
    @lista_cuidadores = ListaCuidadore.all
  end

  # GET /lista_cuidadores/1
  # GET /lista_cuidadores/1.json
  def show
  end

  # GET /lista_cuidadores/new
  def new
    @lista_cuidadore = ListaCuidadore.new
  end

  # GET /lista_cuidadores/1/edit
  def edit
  end

  # POST /lista_cuidadores
  # POST /lista_cuidadores.json
  def create
    @lista_cuidadore = ListaCuidadore.new(lista_cuidadore_params)

    respond_to do |format|
      if @lista_cuidadore.save
        format.html { redirect_to @lista_cuidadore, notice: 'Você entrou na lista de cuidadores.' }
        format.json { render :show, status: :created, location: @lista_cuidadore }
      else
        format.html { render :new }
        format.json { render json: @lista_cuidadore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lista_cuidadores/1
  # PATCH/PUT /lista_cuidadores/1.json
  def update
    respond_to do |format|
      if @lista_cuidadore.update(lista_cuidadore_params)
        format.html { redirect_to @lista_cuidadore, notice: 'Suas informações foram alteradas com sucesso.' }
        format.json { render :show, status: :ok, location: @lista_cuidadore }
      else
        format.html { render :edit }
        format.json { render json: @lista_cuidadore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lista_cuidadores/1
  # DELETE /lista_cuidadores/1.json
  def destroy
    @lista_cuidadore.destroy
    respond_to do |format|
      format.html { redirect_to lista_cuidadores_url, notice: 'Você foi removido da lista.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lista_cuidadore
      @lista_cuidadore = ListaCuidadore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lista_cuidadore_params
      params.require(:lista_cuidadore).permit(:Animal_de_preferencia, :Tipo_de_atendimento, :Data_disponivel, :Cidade, :Estado)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
  base_title = "Patinhas Carinhosas"
  if page_title.empty?
    base_title
  else
    "#{base_title} | #{page_title}"
  end
 end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/instrucoes_helper.rb
module InstrucoesHelper
end

app/helpers/lista_cuidadores_helper.rb
module ListaCuidadoresHelper
end

app/helpers/pag_clientes_helper.rb
module PagClientesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end


  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end


  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
end

app/helpers/sobre_helper.rb
module SobreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/lista_cuidadores/_form.html.erb
<%= form_with(model: lista_cuidadore, local: true) do |form| %>
  <% if lista_cuidadore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lista_cuidadore.errors.count, "error") %> prohibited this lista_cuidadore from being saved:</h2>

      <ul>
      <% lista_cuidadore.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Animal_de_preferencia %>
    <%= form.text_field :Animal_de_preferencia, id: :lista_cuidadore_Animal_de_preferencia %>
  </div>

  <div class="field">
    <%= form.label :Tipo_de_atendimento %>
    <%= form.text_field :Tipo_de_atendimento, id: :lista_cuidadore_Tipo_de_atendimento %>
  </div>

  <div class="field">
    <%= form.label :Data_disponivel %>
    <%= form.datetime_select :Data_disponivel, id: :lista_cuidadore_Data_disponivel %>
  </div>

  <div class="field">
    <%= form.label :Cidade %>
    <%= form.text_field :Cidade, id: :lista_cuidadore_Cidade %>
  </div>

  <div class="field">
    <%= form.label :Estado %>
    <%= form.text_field :Estado, id: :lista_cuidadore_Estado %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lista_cuidadores/edit.html.erb
<h1>Alterando Lista de Cuidadores</h1>

<%= render 'form', lista_cuidadore: @lista_cuidadore %>

<%= link_to 'Back', pag_cuidadores_path %>

app/views/lista_cuidadores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Cuidadores</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <td><th>Preferência</th></td>
      <td><th>Tipo</th></td>
      <td><th>Data</th></td>
      <td><th>Cidade</th></td>
      <td><th>Estado</th></td>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @lista_cuidadores.each do |lista_cuidadore| %>
      <tr>
        <td><%= 'nome cadastrado' %></td>
        <td><%= lista_cuidadore.Animal_de_preferencia %></td>
        <td><%= lista_cuidadore.Tipo_de_atendimento %></td>
        <td><%= lista_cuidadore.Data_disponivel %></td>
        <td><%= lista_cuidadore.Cidade %></td>
        <td><%= lista_cuidadore.Estado %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>



<%= link_to 'Voltar', pag_clientes_path %>

app/views/lista_cuidadores/new.html.erb
<h1>Entrar Para a Lista</h1>

<%= render 'form', lista_cuidadore: @lista_cuidadore %>

<%= link_to 'Voltar', pag_cuidadores_path %>

app/views/lista_cuidadores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Animal de preferencia:</strong>
  <%= @lista_cuidadore.Animal_de_preferencia %>
</p>

<p>
  <strong>Tipo de atendimento:</strong>
  <%= @lista_cuidadore.Tipo_de_atendimento %>
</p>

<p>
  <strong>Data disponivel:</strong>
  <%= @lista_cuidadore.Data_disponivel %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @lista_cuidadore.Cidade %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @lista_cuidadore.Estado %>
</p>

<%= link_to 'Alterar', edit_lista_cuidadore_path(@lista_cuidadore) %> |
<%= link_to 'Voltar', pag_cuidadores_path %>