config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :users
  #resources :login_cuidadores_pgs
  #get 'sign_in' =>  'login_cuidadores_pgs#new'
  #post 'sign_in' => 'login_cuidadores_pgs#create'
  #delete 'sign_out' => 'login_cuidadores_pgs#destroy'
  #resources :login_clientes_pgs
  #get 'entrar' =>  'login_clientes_pgs#new'
  #post 'entrar' => 'login_clientes_pgs#create'
  #delete 'sair' => 'login_clientes_pgs#destroy'
  resources :lista_cuidadores
  resources :pag_cuidadores
  #resources :instrucoes
  #resources :home
  resources :pag_clientes
  #resources :sobre
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :usuarios
  root :to => "home#home"
  get 'ajuda' => 'instrucoes#index'
  get 'sobre'  => 'sobre#sobre'

  get    'login',   to: 'sessions#new'
  post   'login',   to: 'sessions#create'
  delete 'logout',  to: 'sessions#destroy'


=begin
  match 'show_usuario' => 'usuarios#show', via: 'get'
  match 'edit_usuario' => 'usuarios#edit', via: 'get'
  match 'new_usuario' => 'usuarios#new', via: 'get'
  match '' => 'usuarios#create', via: 'post'
  match '' => 'usuarios#update', via: 'patch'
  match '' => 'usuarios#update', via: 'put'
  match '' => 'usuarios#destroy', via: 'delete'
=end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/instrucoes.rb
class Instrucoes < ApplicationRecord
end

app/models/lista_cuidadore.rb
class ListaCuidadore < ApplicationRecord
end

app/models/login_clientes_pg.rb
class LoginClientesPg < Usuario
end

app/models/login_cuidadores_pg.rb
class LoginCuidadoresPg < Usuario
end

app/models/pag_clientes.rb
class PagCuidadore < ApplicationRecord
end

app/models/pag_cuidadores.rb
class PagCliente < ApplicationRecord
end

app/models/pag_login_clientes.rb
class PagLoginCliente < ApplicationRecord
end

app/models/pag_login_cuidadores.rb
class PagLoginCuidadore < ApplicationRecord
end

app/models/sobre.rb
class Sobre < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
   before_save {self.email = email.downcase! }
   attr_accessor :nome, :idade, :email, :cidade, :estado, :ser #:password, :password_confirmation
   validates_presence_of :ser, :idade,:cidade, :estado #:password ,:password_confirmation
   #Confirmação de senha
   #validates_confirmation_of :password
   #Validação do formato de email
   validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
   #Verifica se não existe outro registro de e-mail no banco de dados que tenha a mesma informação;
   validates :email, presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: false }
   validates :nome, presence: true, length: { maximum: 50 }
   has_secure_password
   #Tamanho mínimo da senha
   validates :password, presence: true, length: { minimum: 6}
   # Returns the hash digest of the given string.


end

app/models/usuario.rb
class Usuario < ApplicationRecord
  attr_accessor :nome, :idade, :email, :cidade, :estado, :password, :password_digest
  #valida se o usuarios tiver todos os dados presentes.
  validates_presence_of :nome, :idade, :email, :cidade, :estado, :password
  #verifica se o preenchimento do campo é numérico;
  validates_numericality_of :idade;
  #Confirmação de senha
  validates_confirmation_of :password
  #Validação do formato de email
  validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
  #Verifica se não existe outro registro de e-mail no banco de dados que tenha a mesma informação;
  validates_uniqueness_of :email

  #Tamanho mínimo da senha
  validates :password, length: { minimum: 6}
  has_secure_password



end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sobre_controller.rb
class SobreController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        log_in @user
        if @user.ser == 'cuidador'
          format.html { redirect_to pag_cuidadores_path, notice: 'Bem vindo ao Patinhas Carinhosas Cuidador' }
          format.json { render :show, status: :created, location: @user }
        end
        if @user.ser == 'cliente'
          format.html { redirect_to pag_clientes_path, notice: 'Bem vindo ao Patinhas Carinhosas' }
          format.json { render :show, status: :created, location: @user }
        end
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:nome, :idade, :email, :cidade, :estado, :password, :password_confirmation, :ser)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
  base_title = "Patinhas Carinhosas"
  if page_title.empty?
    base_title
  else
    "#{base_title} | #{page_title}"
  end
 end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/instrucoes_helper.rb
module InstrucoesHelper
end

app/helpers/pag_clientes_helper.rb
module PagClientesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end


  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end


  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
end

app/helpers/sobre_helper.rb
module SobreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/home.html.erb
<div class="center jumbotron">
  <h1>Seja Bem-Vindo ao Patinhas Carinhosas</h1>

  <h2>
    Esta é a página inicial do site
    Patinhas Carinhosas
  </h2>

  <%= link_to "Cadastre-se agora!", new_user_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("dog21.jpg", alt: "cachorrinhos") %>

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Página Inicial</h1>
<br>
<td>Bem-vindo ao (nome do site)</td>
<br>
<br>
<td><%= link_to 'Cadastro de Usuários',usuarios_path %></td>
<br>
<td><%= link_to 'Página dos cuidadores',pag_cuidadores_path %></td>
<br>
<td><%= link_to 'Página dos clientes',pag_clientes_path %></td>
<br>
<td><%= link_to 'Instruções', instrucoes_path %></td>
<br>
<td><%= link_to 'Sobre', sobre_index_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :user_nome %>
  </div>

  <div class="field">
    <%= form.label :idade %>
    <%= form.number_field :idade, id: :user_idade %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :cidade %>
    <%= form.text_field :cidade, id: :user_cidade %>
  </div>

  <div class="field">
    <%= form.label :estado %>
    <%= form.text_field :estado, id: :user_estado %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :user_password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.text_field :password_confirmation, id: :user_password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <p>
      <th>Nome</th>
    </p>
      <th>Idade</th>
      <th>Email</th>
      <th>Cidade</th>
      <th>Estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.nome %></td>
        <td><%= user.idade %></td>
        <td><%= user.email %></td>
        <td><%= user.cidade %></td>
        <td><%= user.estado %></td>
        <p>
        <td><%= link_to 'Mostrar', user %></td>
      </p>
      <p>
        <td><%= link_to 'Editar', edit_user_path(user) %></td>
      </p>
      <p>
        <td><%= link_to 'Deletar', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </p>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Usuario', new_user_path %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for (@user) do |f| %>
    <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inline">

      <%= f.label :nome %>
      <%= f.text_field :nome  %>

      <%= f.label :idade %>
      <%= f.text_field :idade  %>

      <%= f.label :email %>
      <%= f.email_field :email  %>

      <%= f.label :cidade %>
      <%= f.text_field :cidade  %>

      <%= f.label :estado %>
      <%= f.text_field :estado  %>

      <%= f.label :status%>
      <%= f.text_field :ser  %>

      <%= f.label :senha %>
      <%= f.password_field :password  %>

      <%= f.label :password_confirmation, "Confirme a senha" %>
      <%= f.password_field :password_confirmation  %>

      <%= f.submit "Criar minha conta", class: "btn btn-primary" %>

    <% end %>
  </div>
</div>

<%= link_to 'Voltar', login_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @user.nome %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @user.idade %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @user.cidade %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @user.estado %>
</p>

<p>
<%= link_to 'Editar', edit_user_path(@user) %> |
</p>
<p>
<%= link_to 'Voltar', users_path %>
</p>