config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :users
  #resources :login_cuidadores_pgs
  #get 'sign_in' =>  'login_cuidadores_pgs#new'
  #post 'sign_in' => 'login_cuidadores_pgs#create'
  #delete 'sign_out' => 'login_cuidadores_pgs#destroy'
  #resources :login_clientes_pgs
  #get 'entrar' =>  'login_clientes_pgs#new'
  #post 'entrar' => 'login_clientes_pgs#create'
  #delete 'sair' => 'login_clientes_pgs#destroy'
  resources :lista_cuidadores
  resources :pag_cuidadores
  #resources :instrucoes
  #resources :home
  resources :pag_clientes
  #resources :sobre
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :usuarios
  root :to => "home#home"
  get 'ajuda' => 'instrucoes#index'
  get 'sobre'  => 'sobre#sobre'

  get    'login',   to: 'sessions#new'
  post   'login',   to: 'sessions#create'
  delete 'logout',  to: 'sessions#destroy'


=begin
  match 'show_usuario' => 'usuarios#show', via: 'get'
  match 'edit_usuario' => 'usuarios#edit', via: 'get'
  match 'new_usuario' => 'usuarios#new', via: 'get'
  match '' => 'usuarios#create', via: 'post'
  match '' => 'usuarios#update', via: 'patch'
  match '' => 'usuarios#update', via: 'put'
  match '' => 'usuarios#destroy', via: 'delete'
=end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/instrucoes.rb
class Instrucoes < ApplicationRecord
end

app/models/lista_cuidadore.rb
class ListaCuidadore < ApplicationRecord
end

app/models/login_clientes_pg.rb
class LoginClientesPg < Usuario
end

app/models/login_cuidadores_pg.rb
class LoginCuidadoresPg < Usuario
end

app/models/pag_clientes.rb
class PagCuidadore < ApplicationRecord
end

app/models/pag_cuidadores.rb
class PagCliente < ApplicationRecord
end

app/models/pag_login_clientes.rb
class PagLoginCliente < ApplicationRecord
end

app/models/pag_login_cuidadores.rb
class PagLoginCuidadore < ApplicationRecord
end

app/models/sobre.rb
class Sobre < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
   before_save {self.email = email.downcase! }
   attr_accessor :nome, :idade, :email, :cidade, :estado, :ser #:password, :password_confirmation
   validates_presence_of :ser, :idade,:cidade, :estado #:password ,:password_confirmation
   #Confirmação de senha
   #validates_confirmation_of :password
   #Validação do formato de email
   validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
   #Verifica se não existe outro registro de e-mail no banco de dados que tenha a mesma informação;
   validates :email, presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: false }
   validates :nome, presence: true, length: { maximum: 50 }
   has_secure_password
   #Tamanho mínimo da senha
   validates :password, presence: true, length: { minimum: 6}
   # Returns the hash digest of the given string.


end

app/models/usuario.rb
class Usuario < ApplicationRecord
  attr_accessor :nome, :idade, :email, :cidade, :estado, :password, :password_digest
  #valida se o usuarios tiver todos os dados presentes.
  validates_presence_of :nome, :idade, :email, :cidade, :estado, :password
  #verifica se o preenchimento do campo é numérico;
  validates_numericality_of :idade;
  #Confirmação de senha
  validates_confirmation_of :password
  #Validação do formato de email
  validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
  #Verifica se não existe outro registro de e-mail no banco de dados que tenha a mesma informação;
  validates_uniqueness_of :email

  #Tamanho mínimo da senha
  validates :password, length: { minimum: 6}
  has_secure_password



end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/login_clientes_pgs_controller.rb
class LoginClientesPgsController < ApplicationController
  before_action :set_login_clientes_pg, only: [:show, :edit, :update, :destroy]

  # GET /login_clientes_pgs
  # GET /login_clientes_pgs.json
  def index
    @login_clientes_pgs = LoginClientesPg.all
  end

  # GET /login_clientes_pgs/1
  # GET /login_clientes_pgs/1.json
  def show
  end

  # GET /login_clientes_pgs/new
  def new
    @login_clientes_pg = LoginClientesPg.new
  end

  # GET /login_clientes_pgs/1/edit
  def edit
  end

  # POST /login_clientes_pgs
  # POST /login_clientes_pgs.json
  def create
    @login_clientes_pg = LoginClientesPg.new(login_clientes_pg_params)
    #@login_clientes_pg = login_clientes_pg.find_by(email: params[:login_clientes_pg][email:].downcase)
      #if @login_clientes_pg && login_clientes_pg.authenticate(params[:login_clientes_pg][:senha])
        #entrar @login_clientes_pg

    respond_to do |format|
      if @login_clientes_pg.save
        format.html { redirect_to @login_clientes_pg, notice: 'Login clientes pg was successfully created.' }
        format.json { render :show, status: :created, location: @login_clientes_pg }
      else
        format.html { render :new }
        format.json { render json: @login_clientes_pg.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /login_clientes_pgs/1
  # PATCH/PUT /login_clientes_pgs/1.json
  def update
    respond_to do |format|
      if @login_clientes_pg.update(login_clientes_pg_params)
        format.html { redirect_to @login_clientes_pg, notice: 'Login clientes pg was successfully updated.' }
        format.json { render :show, status: :ok, location: @login_clientes_pg }
      else
        format.html { render :edit }
        format.json { render json: @login_clientes_pg.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /login_clientes_pgs/1
  # DELETE /login_clientes_pgs/1.json
  def destroy
    @login_clientes_pg.destroy
    respond_to do |format|
      format.html { redirect_to login_clientes_pgs_url, notice: 'Login clientes pg was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_login_clientes_pg
      @login_clientes_pg = LoginClientesPg.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def login_clientes_pg_params
      params.permit(:nome, :idade, :email, :cidade, :estado, :senha, :senha_confirmation,:password_digest)
      #params.require(:usuario).permit(:nome, :idade, :email, :cidade, :estado, :senha, :senha_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
  base_title = "Patinhas Carinhosas"
  if page_title.empty?
    base_title
  else
    "#{base_title} | #{page_title}"
  end
 end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/instrucoes_helper.rb
module InstrucoesHelper
end

app/helpers/login_clientes_pgs_helper.rb
module LoginClientesPgsHelper
end

app/helpers/pag_clientes_helper.rb
module PagClientesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end


  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end


  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
end

app/helpers/sobre_helper.rb
module SobreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/login_clientes_pgs/_form.html.erb
<%= form_with(model: login_clientes_pg, local: true) do |form| %>
  <% if login_clientes_pg.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(login_clientes_pg.errors.count, "error") %> prohibited this login_clientes_pg from being saved:</h2>

      <ul>
      <% login_clientes_pg.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/login_clientes_pgs/edit.html.erb
<h1>Editing Login Clientes Pg</h1>

<%= render 'form', login_clientes_pg: @login_clientes_pg %>

<%= link_to 'Mostrar', @login_clientes_pg %> |
<%= link_to 'Voltar', login_clientes_pgs_path %>

app/views/login_clientes_pgs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Login Clientes Pgs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @login_clientes_pgs.each do |login_clientes_pg| %>
      <tr>
        <td><%= link_to 'Mostrar', login_clientes_pg %></td>
        <td><%= link_to 'Alterar', edit_login_clientes_pg_path(login_clientes_pg) %></td>
        <td><%= link_to 'Destruir', login_clientes_pg, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo login', new_login_clientes_pg_path %>

app/views/login_clientes_pgs/new.html.erb
<h1>Login de Clientes Pg</h1>

<%= form_for :login_clintes_pg, url: entrar_path do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :senha %><br />
    <%= f.password_field :senha, autocomplete: "off" %>
  </div>
  <div class="actions">
    <%= f.submit "Entrar" %>
  </div>
<p>Novo aqui? <%= link_to "Cadastre-se agora!", new_usuario_path %></p>
<% end %>

<%= link_to 'Voltar', root_path %>

app/views/login_clientes_pgs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_login_clientes_pg_path(@login_clientes_pg) %> |
<%= link_to 'Back', login_clientes_pgs_path %>